volumes:
  pgdata:

networks:
  esnet:

services:
  react:
    build:
      context: /frontend
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"
  go:
    build:
      context: /backend
      dockerfile: Dockerfile
    container_name: go
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_DEFAULT_USER=${DB_DEFAULT_USER}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - IS_PRODUCTION=${IS_PRODUCTION}
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    user: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    

