CREATE TABLE IF NOT EXISTS likes 
(
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    post_id INT NOT NULL,	
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
	FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
)