CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,
	username TEXT UNIQUE,
	password TEXT NOT NULL,
	role TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS topics
(
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
    user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS posts
(
	id SERIAL PRIMARY KEY,
	header TEXT NOT NULL,
	body TEXT NOT NULL, 
	created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id INT NOT NULL, 
	topic_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
	FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
	id SERIAL PRIMARY KEY,
	body TEXT NOT NULL,
	created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id INT NOT NULL,
	post_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
	FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS refresh_tokens 
(
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	token VARCHAR(255) NOT NULL UNIQUE,
	expires_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	is_revoked BOOLEAN DEFAULT FALSE,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
